### ISSUE TITLE
Dataset does not contain all areas?

### ISSUE THREAD

**Issue by megancooper** [OpenBeta/climbing-data#2]
I was looking through the dataset and it seems like higher-level areas are being excluded, and only the "lowest" level areas are being included in the dataset. For example, the area `Barton Creek Greenbelt` is [designated as an area](https://www.mountainproject.com/area/105905087/barton-creek-greenbelt), but is not in the dataset. A [lower-level area that is inside `Barton Creek Greenbelt`](https://www.mountainproject.com/area/105991035/gus-fruh), `Gus Fruh` *is* included in the dataset. Is there any reason these higher order areas are being excluded?

**Comment by vnugent** [comment]
Since there isn't a convention on how areas and subareas hierarchy should be organized on MP, it's difficult for the Python script to decide which level is more important than other. For example:

Texas > Austin area > Barton Creek Greenbelt > Gus Fruh wall

Nevada > Southern Nevada > Red Rock > Calico Basin > Kraft Mountain Area > Sunny and Steep wall

In the end I decided to capture only the "leaf" wall. Can you tell me a bit more about your use case where you need to know all the parents?

**Comment by megancooper** [comment]
Ahh okay, maybe it makes sense for all of these areas to be classified as areas, but to represent the hierarchy somehow within the dataset. Basically I'm working on an app that needs to allow for any area as a search term.

**Comment by vnugent** [comment]
I created a temporary branch (`texas-with-areas`) where area hierarchy is included in each route.

Texas:  https://github.com/OpenBeta/climbing-data/blob/texas-with-areas/openbeta-routes-tx.zip

```
{
  ...,
  
  "mp_path": "Austin Area|Barton Creek Greenbelt|Seismic Wall A.K.A. Maggie's Wall"

}
```

**Comment by megancooper** [comment]
@vnugent Thank you so much, we'll check this out!

**Comment by vnugent** [comment]
Let us know if you still have any questions.
